### ISSUE TITLE
Interactive Tutorial

### ISSUE THREAD

**Issue by girng** [crystal-lang/crystal-website#102]
Preface: _(if this issue causes any issues just tell me and I will pm Brian on the forum instead)._  I was browsing  the [Chicago meetup](https://www.meetup.com/Crystal-Lang-Chicago/events/bbhsjryzpbkb/) website and noticed Brian mentioned Haskell. I've read Ary uses Haskell as well, so I decided to check it out. I've heard about Haskell before, but I know it's a functional language so I've stayed away ( my mind just doesn't work with functional languages ).  

Anyways.. so I went to [Haskell's website](https://www.haskell.org/) and [started to complete the interactive tutorial](https://i.gyazo.com/501d5e481862718cc7480c21359272de.png). You type in *actual* code, and if it matches what the tutorial wants you to learn, it will advance the user to the next section.

I've never done a tutorial like this, and IMHO it felt amazing and a great learning experience. I think it would be very cool to have something similar on Crystal's website!

**Comment by straight-shoota** [comment]
Duplicate of crystal-lang/crystal#4462

Could you please post this comment there to keep the discussion in a single place?

**Comment by girng** [comment]
@straight-shoota Awww, didn't see that.  Yeah I will, thank you
