### ISSUE TITLE
500 errors on index

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal-website#108]
I am getting a 500 error when navigateing to index on the root domain.

<img width="855" alt="Screen Shot 2020-05-18 at 10 53 17 PM" src="https://user-images.githubusercontent.com/1045155/82283003-c1750700-995a-11ea-87ae-32d9a7d3e29e.png">

**Comment by straight-shoota** [comment]
Can't reproduce this. Maybe a temporal glitch...

**Comment by straight-shoota** [comment]
I'm getting connect timeouts on https://www.crystal-lang.org though.
It resolves to different addresses than crystal-lang.org
@wontruefree Did you try to connect to www.crystal-lang.org or crystal-lang.org?

**Comment by wontruefree** [comment]
I tried www.crystal-lang.org and crystal-lang.org with http and https last night.
I tried multiple browsers and reset the cookies and it still failed but weirdly curl worked.

It works for me this morning so it is no longer a problem but I wanted to make an issue in case it was wide spread.

**Comment by waj** [comment]
The website is just static content hosted at S3 + CloudFront, so a 500 error sounds like a glitch on AWS.

@straight-shoota I don't know why we didn't realise before, but `www.crystal-lang.org` points directly to the S3 bucket (just for redirection), so it doesn't support https. I'll fix that!

**Comment by wontruefree** [comment]
sounds like whatever this is was resolved so I am going to close this issue.
