### ISSUE TITLE
Contribution Guide?

### ISSUE THREAD

**Issue by samueleaton** [crystal-lang/crystal-website#11]
Is there a contribution guide for the website? What framework is being used to compile? If I'm just changing markup, do I just edit the `.haml` file, `.html` files, or both?

**Comment by mverzilli** [comment]
Hi @samueleaton! We added some minor details to `README.md` in the `redesign` branch, which is soon to be merged. It's just a Jekyll site, so most of the "How To's" can actually be addressed with the Jekyll docs. I'm closing this now, but if there's any particular aspect you want to address feel free to continue the discussion (however, you may want to wait until we publish the new design this week).
