### ISSUE TITLE
Cache busting of assets

### ISSUE THREAD

**Issue by matiasgarciaisaia** [crystal-lang/crystal-website#12]
The site assets (css, js) are cached by the browsers, so the site can look ugly between updates.

We should use some [asset version hasher](https://philna.sh/blog/2016/06/28/asset-pipelines-with-jekyll-assets/) or something like that to avoid this issue.

**Comment by vtiffenberg** [comment]
Used suggestion from PR #16 and added jekyll-assets. The commit linked above and the following 3 have all the changes.
