### ISSUE TITLE
"Install" guide/link

### ISSUE THREAD

**Issue by matiasgarciaisaia** [crystal-lang/crystal-website#13]
There's no "Install" section or link in the website. We should probably include one.

**Comment by mverzilli** [comment]
Maybe we should just point the first "Read more" link to "Installation" at crystal-lang.org/docs

**Comment by matiasgarciaisaia** [comment]
We actually have one big `INSTALL` button on the new website, properly linking to the docs.

<img width="735" alt="screen shot 2017-04-06 at 2 19 00 pm" src="https://cloud.githubusercontent.com/assets/5470539/24767055/0fd54b8e-1ad4-11e7-8197-5ea8e8b9903a.png">

This is solved :)
