### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal-website#137]
With bintray going down we have moved our binary package distribution to OBS (https://github.com/crystal-lang/crystal/issues/10626#issuecomment-829554125) and need to update the installation instructions.

OBS has a landing page for installation instructions at https://software.opensuse.org//download.html?project=devel%3Alanguages%3Acrystal&package=crystal
We could consider linking that directly and don't have to care too much about keeping the instructions in sync.
It's not easy to incorporate with the current content architecture though. So it's probably easier for now to just update the existing instructions and adapt them to OBS as good as possible.

The installer script needs to be updated as well. And that's a bit more work to do correctly because OBS has separate repositories for every distro version. So instead of a single deb repository, we not have 10. And 17 rpm repos. I haven't even activated all that are available.

**Comment by Stig124** [comment]
Doing that, linking the correct repo on every page, will finish in no time

**Comment by Stig124** [comment]
I suggest to only remake installation instruction for the most up-to-date distros and let people which run the other distros get them on OBS

**Comment by straight-shoota** [comment]
I think all issues with updating installation instructions have been addressed.
