### ISSUE TITLE
Show the governance bodies

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal-website#140]
With adopting https://github.com/crystal-lang/crystal-book/pull/512 there will be two groups of people taking responsibility for the Crystal project: The steering council and the core team.
To be transparent on who is a member of these groups, we should have a public list for that.
Currently, only membership of the @crystal-lang org on Github (somewhat) documents core team membership. However, it's incomplete and imprecise, and not very accessible.

I suggest adding a list of steering council and core team members to the website, probably https://crystal-lang.org/community is the best place for that. There should also be room to list alumni.

Recently I ran into a nice looking example at https://solidus.io/community/#core-team
We don't necessarily need so much detail and special fotos, but it looks good and gives more personality to an administrative body.

I think the essential information for every member is:

* Real name
* Membership of steering council and/or core team
* Github and forum handles

Non-essential but IMO also important:

* Picture (ideally a foto)
* info about being employed vs. volunteer member

I could think of more, optional things to add. But small steps first.

**Comment by beta-ziliani** [comment]
Given that we added the gov doc in the book, shouldn't this be there too?

**Comment by straight-shoota** [comment]
I would look at the community page for this. That doesn't mean it has to be there, of course. A link to the book (or anywhere else) would be fine.

So yes, it could as well be in the book. I think I was considering the book as being a more permanent source of knowledge, and a list of people currently in charge is of more ephemeral nature.

But I'm really fine with either. The line between book and website is really blurry and we'll probably need to work out a few things (see #98 for example). The reason is that the book started as a git book containing the language reference but since then grew to collection of many different documentation resources.

**Comment by straight-shoota** [comment]
It seems this would actually be too much content and out of scope for the community page.

I figured there should be a separate page presenting the team. Not just the Core Team, but the entire gang. That includes honorary mention of former Core members, non-Core members providing administrative support, and in fact every single contributor that helps driving this project.

I did not add a separate section for the Steering Council. All members are already listed on the Core Team and identified as members of the Steering Council.

Preview is available here: https://deploy-preview-1--hungry-jepsen-05c3ee.netlify.app/team/

@crystal-lang/crystallers Please let me know what you think. Does the presentation format fit?

The body copy still needs some polishing probably.

**Comment by bcardiff** [comment]
Looks good! Visual feedback: The alumni alignment is a bit off. 

I didn't notice where this page will be linked from.

The rest of contributors is dynamic or is imported data?

**Comment by straight-shoota** [comment]
> The alumni alignment is a bit off.

Sry, in what direction is it off?

> I didn't notice where this page will be linked from.

That's still to be determined. There should probably be links from the Community page and the Governance Document. But in terms of navigation tree, IDK... maybe a separate menu entry for now?

The contributors are auto-generated. The image is provided by Open Collective: https://opencollective.com/crystal-lang/contributors.svg?width=960

**Comment by beta-ziliani** [comment]
This is awesome @straight-shoota ! <3

**Comment by bcardiff** [comment]
The alumni "cards" does not have a fixed width. On mobile this make the alignment centered, with the photos in different positions. While the core team is left aligned. On desktop it looks good.

![IMG_A80A27D66424-1](https://user-images.githubusercontent.com/459923/120087801-7a6b3700-c0c1-11eb-88ec-516662899b38.jpeg)

> The contributors are auto-generated. The image is provided by Open Collective: https://opencollective.com/crystal-lang/contributors.svg?width=960

Nice. I though OC would generate the image for financial contributors, but these are the code contributors it seems.
