### ISSUE TITLE
Identity and Design

### ISSUE THREAD

**Issue by flagello** [crystal-lang/crystal-website#19]
Considering [2017 may see the bright light of 1.0](https://crystal-lang.org/2016/12/29/crystal-new-year-resolutions-for-2017-1-0.html), it may be a good time to start discussing the definition of Crystal visual personality and communication style.

I would aim to make Crystal's elegance and efficiency-via-essentiality _universal_ and inherently _visible_ in all of its forms and voices. Other than being, I suggest to accompany developer perception and experience into elegance and essentiality.

<br>

I took the liberty of starting from the logo to kickstart things up. I would love to see other suggestions from fellow designers or feedback and ideas from the community. I do not consider this direction to be of particular value.

![logo-0](https://cloud.githubusercontent.com/assets/649779/23007093/3fb5780a-f406-11e6-96c8-38e20297af36.png)

![logo-3](https://cloud.githubusercontent.com/assets/649779/23007564/d06652b8-f409-11e6-8a2f-6290f997f60a.png)

![logo-1](https://cloud.githubusercontent.com/assets/649779/23007589/ee95b36e-f409-11e6-83fe-3af92d07bdff.png)

![logo-2](https://cloud.githubusercontent.com/assets/649779/23007579/e4bd73d6-f409-11e6-89fb-4eec5f980ff0.png)

![logo-4](https://cloud.githubusercontent.com/assets/649779/23007643/0004da6c-f40a-11e6-901d-6ddca97404b9.png)

<br>
<br>

I then focused on the website. Please, again, share any thought.

`1440 ⨉ 900 (@2) [Fullscreen MacBook Pro Retina]`
![0](https://cloud.githubusercontent.com/assets/649779/23007688/810d2b8c-f40a-11e6-84a6-0e44e1ae5e61.png)

`375 ⨉ 667 (@2) [Fullscreen iPhone 7]`
<img width="375" height="667" src="https://cloud.githubusercontent.com/assets/649779/23007818/66162490-f40b-11e6-880a-77db3f284799.png" />

<br>
<br>

I used `#862E9C` (purple) as a variant of the `#2e1052` that appears in the docs.

I suggest the persistence of **Moriston** for `<hN>` + `<p>` and **SF Mono** for `<code>`. _Forma DJR_ may be a potential alternative for `<hN>` + `<p>`. Within both environments, the view scrolls to more details (raw information and full navigation). For desktop, a more prominent action to discover details may aid interaction (possibly “Learn More” or “Get Started”).

I suggest to constrain the information-on-impact to the essential. Should my direction be determined to be of value, what is essential is of course up for research and debate. Currently presented information is in fact indicative.

<br>
<br>

(Thanks! :)

**Comment by sdogruyol** [comment]
This is awesome 😍

**Comment by molovo** [comment]
Big fan of this. I hate programming sites which hide code examples away behind a wall of text. Front and center is always better. Looking forward to seeing how this develops.

**Comment by RX14** [comment]
There's actually a current "open-secret" effort to redesign the website happening in the [redesign](https://github.com/crystal-lang/crystal-website/tree/redesign) branch of this repo. Here's some screenshots:

![Above the fold](https://aww.moe/oigk29.png)
![Examples](https://aww.moe/tk27fb.png)
![Sponsors + Blog](https://aww.moe/l5n5no.png)
![Footer](https://aww.moe/yzpdbs.png)
![Blog Post](https://aww.moe/opgsac.png)

Mobile... needs some more work:
![](https://dl2.pushbulletusercontent.com/WGsvohdyP1sYIS8lQILSbmMYoaK1CZjc/Screenshot_20170216-093222.png)

**Comment by idchlife** [comment]
Wow! I like both those styles. They are great! But somehow, don't you all think that purple color is not that user friendly as someone would think? I'm not a designer, but I'm more please with dark DOC theme rather than with purple white API page theme. Purple (at least this one) kinda seems like randomly chosen in dreamweaver and thrown into website.

**Comment by paulcsmith** [comment]
I personally prefer black and white as the main identity and I love the current logo. I like a lot of the ideas here though. 

A few months ago someone also did a redesign that looks really nice IMO https://www.google.com/amp/s/vaporsoft.net/redesigning-crystal-lang-org/amp/?client=safari

Might be worth checking out to get some more ideas

**Comment by spalladino** [comment]
Thanks a lot @flagello for the contribution!! The design looks great indeed. However, as @RX14 pointed out, we are already way into the process of redesigning the site. Since the surprise has already been spoiled (jk), you can check how it's going at stg.crystal-lang.org.

Also, you brought up an important thing that we have been overlooking so far, that is the communication style, ie how CrystalLang speaks from Twitter, blog, and other accounts, regardless of who is the person actually writing. We'll discuss this with Manas marketing manager to get some ideas on how to handle it.

I'll share this with our designer, @jkicillof, so he can go through the ideas here. Thanks again!

**Comment by kirbyfan64** [comment]
Ehh...not to be a downer, but the purple looks really odd there to me...

**Comment by RX14** [comment]
Just as another data point on the purple, I actually quite like it. We already use a purple on the [api docs](https://crystal-lang.org/api/) and I think it looks super nice. In fact, I think that the redesign could do with a highlight colour (although not necessarily the same purple).

**Comment by flagello** [comment]
Thank you guys! I missed the redesign branch. I understand your approach may already be definitive. It's certainly an improvement, but I would be interested in continuing exploring other directions overall (site, guidebook, docs).

I would consider to encourage further community contributions and feedback in order to foster openness and harvest value that would otherwise be missed. More so in a front that had not received significant attention from the community itself.

<br>

(@kirbyfan64 I too prefer a monochrome palette.)

**Comment by spalladino** [comment]
@flagello if you're interested in exploring other sections, feel free to take a look at what we have designed so far for the [book](https://invis.io/87AHPDM4H) and the [API reference](https://invis.io/RJAHPFGEX). We haven't started implementing them, so suggestions are welcome. Keep in mind though that we fully give our designer the last word on how the site should look like ;-)

**Comment by RX14** [comment]
@spalladino again, I think that trying a vary sparing touch of colour would be nice. It feels a little boring to me.
