### ISSUE TITLE
Crystal Language -- What is it, and why is there no description of that ANYWHERE on the website?

### ISSUE THREAD

**Issue by zipzit** [crystal-lang/crystal-website#195]
Elevator speech = 1 or 2 minutes.  

Crystal Language.  Overview.  What is it?  And why would I want to use it?   

I'm not seeing a description of Crystal language anywhere that I can find on the website or on Github.

I see Install / Learn / Try
I can see examples of code.  I can see how to install it (but, why would I do that if I don't know what it is I'm installing?)

Possible somewhere, someplace to add a few sentences to describe what Crystal language is?  

[docs](https://crystal-lang.org/docs/) not much better.. 

And from:  https://crystal-lang.org/reference/

> Welcome to the documentation for the Crystal language.
> Crystal is a language for humans and computers. These materials help humans understand the language and its ecosystem.

Wait, that's your description? There are a whole bunch of software languages that can use that description. Not good.  Actually just not good enough  I gotta believe somebody there knows what this thing is.    Can we add a helpful description somewhere on the site?  

And obviously this is just one person's opinion.  No offense intended.  You can only be a virgin visitor to the site once.  

At this point my take away is crystal language folks are very poor communicators.. if they can't communicate the easy stuff, what else is obfuscated?  Is that really where I want to spend time?   Run, run away from this whole stack.

**Comment by straight-shoota** [comment]
Resolved by #416
