### ISSUE TITLE
API links broken

### ISSUE THREAD

**Issue by ricardobeat** [crystal-lang/crystal-website#2]
I'm guessing this is because versioning was added to the URLs. This is breaking all existing links from Google (first result searching for 'crystal-lang $api_feature'):

<img width="631" alt="google " src="https://cloud.githubusercontent.com/assets/97396/16469539/eaac2fda-3e51-11e6-80bc-bad692c3a494.png">

Linking to https://crystal-lang.org/api/toplevel.html should redirect to latest version at https://crystal-lang.org/api/XX/toplevel.html, or at least an `/api/latest/xxx` endpoint created (in that case a 301 redirect in the old URLs would be in order to not lose pagerank).

**Comment by bcardiff** [comment]
api URIs are back.
/api/IO.html ----permanent---> /api/latest/IO.html ---temporal---> /api/0.18.6/IO.html . 

The first redirect is performed on a 404, so it might lead to infinite loops.
But at least all links around work.
But they should be changed to /api/latest/ .
