### ISSUE TITLE
The docs page has a dead link to the language reference

### ISSUE THREAD

**Issue by raw-bin** [crystal-lang/crystal-website#217]
Hi.

Navigating to: https://crystal-lang.org/docs/ and attempting to click the link to the Language Reference results in a 404.

Thanks

**Comment by matiasgarciaisaia** [comment]
Thanks for the report, @raw-bin!

Can you double-check - it should be working right now.

We've added the fix to crystal-lang/crystal-book#561, too.

**Comment by raw-bin** [comment]
Thanks @matiasgarciaisaia! :)

All good now!

Robin
