### ISSUE TITLE
Accessibility issues across the site

### ISSUE THREAD

**Issue by chances** [crystal-lang/crystal-website#220]
Considering users with low-to-no vision and those who use screen readers:

- Many images are missing alternative text
- Inadequate color contrast of many spans of text
- etc.

See [this report](https://wave.webaim.org/report#/https%3A%2F%2Fcrystal-lang.org) from [WebAIM](https://webaim.org/)'s web accessibility evaluation tool.

**Comment by straight-shoota** [comment]
Thanks for reporting. We've started working on a redesign of the website, which will hopefully solve these issues.

**Comment by straight-shoota** [comment]
It's taken some time but most a11y issues should now be resolved with the redesign (#416).
