### ISSUE TITLE
Switch comments to discourse

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal-website#240]
Currently, we're using Disqus for comments on blog posts. 

Our forum at https://forum.crystal-lang.org/ runs on Discourse which can be used as a comment provider as well.
Integration works with some configuration on the forum and a small JavaScript to embed on the website. That's similar to the way we're integrating Disqus currently.

Instructions are here: https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963

Pros:

* We're removing an additional service.
* Interaction becomes easier for users: You only need a forum account to write a comment. There's no need to register with Disqus.
* Comments on blog posts have better visibility on the forum. Currently they often go pretty much unnoticed.

Cons:

Any?

**Comment by Sija** [comment]
I'm totally in favour of switching away from Disqus, not only because it's another 3rd party service, but also because of JS-bloat their plugin is adding and especially in the light of their lack of respect for users' privacy, see https://techcrunch.com/2021/05/05/disqus-facing-3m-fine-in-norway-for-tracking-users-without-consent/

**Comment by beta-ziliani** [comment]
The only cons I see to the migration is that we'll lose the comments. But I think this is a necessary step to take. Maybe we can find a way of converting existing comments into plain html 🤔

**Comment by straight-shoota** [comment]
For a start, we can keep the old comments on existing posts in place just as they are. That's the easiest thing. Then we can think about exporting old comments from discourse as an independent action.

**Comment by Sija** [comment]
> For a start, we can keep the old comments on existing posts in place just as they are. That's the easiest thing. Then we can think about exporting old comments from discourse as an independent action.

@straight-shoota That IMO is gonna be a pretty clumsy UX. There's already a disqus importer [script](https://github.com/discourse/discourse/blob/5d6e8fdff0a8854679a9e553de257feb56e3e6ba/script/import_scripts/disqus.rb), so why not use that?

**Comment by straight-shoota** [comment]
Sure, could do that as well. But I don't think it's clumsy. Some posts have comments from X, others from Y. You won't see both of them on the same page.

**Comment by straight-shoota** [comment]
My concern is that it increases the problem space. If we need A for B to happen, than B is more distant than if we can do B independently and follow up with A later. And I'd very much like to switch to Discourse as comment engine sooner than later.

**Comment by straight-shoota** [comment]
Let's try the migration script. If it just works, we probably have the easiest solution by far.
