### ISSUE TITLE
Implement 404 error page style

### ISSUE THREAD

**Issue by pmallol** [crystal-lang/crystal-website#25]
Version 466d08d

Style for [404 error page](https://projects.invisionapp.com/d/main#/console/9985608/222578713/preview) not implemented yet.

**Comment by mverzilli** [comment]
Fixed through 404.html and AWS config

**Comment by pmallol** [comment]
404 is not centered

![screen shot 2017-03-22 at 7 45 42 pm](https://cloud.githubusercontent.com/assets/9214460/24224129/3c5579ec-0f38-11e7-8c60-3a8f09fc1c7a.png)

**Comment by pmallol** [comment]
Ok in version  b986c84
