### ISSUE TITLE
Show feeds

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal-website#267]
With the inclusion of #259 we noted there's no place to find the feeds

**Comment by straight-shoota** [comment]
Just to clarify, we currently have two news feeds:

* Blog posts (`feed.xml`)
* Releases (`releases/feed.xml`)

For the releases feed, it's probably sufficient to have a link on the releases index (and maybe each release page).

The blog posts feed is most important and should be visible in the main layout on each page. 

An idea for that was to place a feed icon in the navigation menu, next to the GitHub icon.

**Comment by straight-shoota** [comment]
Resolved by #614
