### ISSUE TITLE
[Home] Change all 'Read more' links to show just the link text instead of an url

### ISSUE THREAD

**Issue by pmallol** [crystal-lang/crystal-website#28]
Version 9e35319

![screen shot 2017-03-21 at 12 24 12 pm](https://cloud.githubusercontent.com/assets/9214460/24155139/c39e43b4-0e31-11e7-8564-96e07f57da38.png)

Change url links to a text link as in the design proposal
![screen shot 2017-03-21 at 12 28 04 pm](https://cloud.githubusercontent.com/assets/9214460/24155298/305acbd0-0e32-11e7-8f2e-244be4547734.png)

**Comment by pmallol** [comment]
I'm gonna fight for this one, I really think that adding the doc's section to each 'Read more about [e.g: Syntax and Semantics]', even if it can be a bit redundant, it gives the interested user a hint on what kinds of things she/he will be able to learn by clicking on it.
I guess it's ok how it is now being so close to finally launching the site but I hope you'll reconsider :)

**Comment by mverzilli** [comment]
Ok, you win :P. 

https://github.com/crystal-lang/crystal-website/commit/84f813f9c8b2a6dfa7bef2a43535d2ef581aa80f

**Comment by pmallol** [comment]
Ok in version c8873ee
