### ISSUE TITLE
Missing installation for windows

### ISSUE THREAD

**Issue by wonderix** [crystal-lang/crystal-website#299]
There should be a description on how to install crystal on windows using scoop.

If someone is already working on a solution for #99, you can close this issue. Otherwise I could provide a short description.

**Comment by straight-shoota** [comment]
I'm not aware of any work having started on this. Formulating the instructions for Windows are definitely independent of https://github.com/crystal-lang/crystal-website/issues/99. So please go ahead! 🙇‍♂️
