### ISSUE TITLE
[Mobile] Minor details

### ISSUE THREAD

**Issue by pmallol** [crystal-lang/crystal-website#30]
Version 9e35319, tested on iPhone 5s

- [x] Home header buttons are missing a border `border: 2px solid #ffffff;`
![img_4037](https://cloud.githubusercontent.com/assets/9214460/24161600/a32ab31c-0e43-11e7-91e1-0a18ebaba8f5.PNG)

- [x] "Crystal language, born & raised at Manas" should have text in color black
![img_4038](https://cloud.githubusercontent.com/assets/9214460/24161667/d7ea3988-0e43-11e7-8355-ee77d227fa2a.PNG)

- [x] Collapsed menu shows links with a non desirable `border-bottom: 1px solid #777777;` 
![img_4035](https://cloud.githubusercontent.com/assets/9214460/24161170/751d386a-0e42-11e7-9488-e4b9c9c208d1.PNG)

- [x] 'Community' title is larger than screen width
![img_4034](https://cloud.githubusercontent.com/assets/9214460/24161182/7c18e9d4-0e42-11e7-8c3c-ef460cb360c0.PNG)

- [ ] In Sponsors, the 'Since' date appears shrinked in three lines
![img_4033](https://cloud.githubusercontent.com/assets/9214460/24161195/846bba62-0e42-11e7-8a88-5458cbb0095f.PNG)

- [x] Many sections should appear centered but instead are shown aligned to the left
For example in Sponsors, the Want to become a sponsor? section:
![img_4032](https://cloud.githubusercontent.com/assets/9214460/24161211/8d65f038-0e42-11e7-8973-55f39f346dc9.PNG)

**Comment by mverzilli** [comment]
The "since" item is pretty graceful as it is, so I think we can close this issue.

**Comment by pmallol** [comment]
Everything ok in version 6165a6a
