### ISSUE TITLE
Bountysource URL instructions are wrong

### ISSUE THREAD

**Issue by matiasgarciaisaia** [crystal-lang/crystal-website#40]
The instructions for adding your URL to the sponsors list are wrong on the new website. All you have to do is to add a Website to [your Bountysource profile](https://www.bountysource.com/settings).

<img width="282" alt="screen shot 2017-04-06 at 2 15 40 pm" src="https://cloud.githubusercontent.com/assets/5470539/24766942/9e9a33e4-1ad3-11e7-82e3-73e506255c26.png">

**Comment by pmallol** [comment]
Ok in Version c8873ee
