### ISSUE TITLE
Sponsor's logos have all the same size

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal-website#405]
This is in contradiction with what the OC perks claim:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/5183634/216350659-c35da4b5-1e21-450e-a00b-018d9a3309b2.png">

We need to account for three different sizes (S, M, L)

**Comment by straight-shoota** [comment]
Resolved by https://github.com/crystal-lang/crystal-website/pull/416
