### ISSUE TITLE
Explicit the packages that are not official

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal-website#478]
Those packages that are not maintained by us should loudly say they aren't.

**Comment by straight-shoota** [comment]
Ref: https://github.com/crystal-lang/crystal-website/pull/472#issuecomment-1642019936

> Sources that are not owned by us are distribution package repositories like BSD ports and packages, apk (Alpine), portage  (Gentoo), pacman (Arch Linux).
>And most repos for 3rd party package managers: asdf, homebrew, scoop, termux, nix.
>
> We can add notes that they are not official and may not be up to date.

**Comment by straight-shoota** [comment]
Resolved by https://github.com/crystal-lang/crystal-website/pull/540
