### ISSUE TITLE
Blank name sponsors shouldn't be listed

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal-website#516]
ref: https://github.com/crystal-lang/crystal-website/pull/511/files#r1385040554

<img width="909" alt="image" src="https://github.com/crystal-lang/crystal-website/assets/5183634/c2a62b4c-ac66-4211-9321-4c1a88c59739">

**Comment by straight-shoota** [comment]
If we remove sponsors with an empty name, their alltime contributions wouldn't be listed, though. So unlisting them alters the dataset.

I think this is fine. Maybe we could use a replacement for the empty name (such as "anonymous") to improve the visuals.

**Comment by beta-ziliani** [comment]
but the dataset is bogus by definition. there are the original donors, plus the lack of history from bountysource. I was going to go with "anonymous", but I don't think this is relevant enough to spend time or to care. note that we are already filtering "guest" and "incognito".
