### ISSUE TITLE
Install page crashes Chrome

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal-website#579]
The [install page](https://deploy-preview-416--crystal-website.netlify.app/install/) currently crashes Chrome. It works fine on Firefox. Other pages work fine.
There's no error reporting in the browser, but I've been able to narrow it down to this line in the CSS:

https://github.com/crystal-lang/crystal-website/blob/f193d5ca0b4b807f230bc989be5dad70acb8bf46/_sass/pages/_install.scss#L13

No idea what issue Chrome might be having with basline alignment 🤷

**Comment by beta-ziliani** [comment]
Was it reported?

**Comment by straight-shoota** [comment]
Looks like it's already fixed upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1483201

**Comment by straight-shoota** [comment]
There's no point in keeping this open after the workaround in #580.
