### ISSUE TITLE
Release notes are utterly outdated

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal-website#58]
On the homepage, section `Release Notes`, last entry is from 22 Nov 2016. More than a year ago. Anyone looking there would come to the conclusion that Crystal has not seen a release since then, i.e. it's more or less dead.

There are two options: Either add release notes for all recent releases and keep this section updated or remove it entirely. Better no information than information that is misleading.

As a very simple solition it could just link to the [release notes on Github](https://github.com/crystal-lang/crystal/releases).
I would prefer to have proper release notes for any release. It doesn't have to be as detailed as the recent entries from 2016, but mentioning the highlights would be awesome. And a reference to the detailed list on Github.

If the section is to stay, there should be some mechanism to ensure a release note post is prepared for any release. I think this could fit very well in the new workflow of having a PR for each release including it changelog. Whoever opens this PR on the main repo should make sure to open an issue here. I think this can be provided by the community, no need to put a core dev on this (unless they want to).

**Comment by RX14** [comment]
I started this for 0.24.1 but didn't get far before switching to working on windows, and I probably won't have time for a while...

I think this is very important though.
