### ISSUE TITLE
Snake case instead of camelcase ?

### ISSUE THREAD

**Issue by thooams** [crystal-lang/crystal-website#6]
In Doc: https://crystal-lang.org/docs/using_the_compiler/index.html

The name of project is in Camelcase not in Snake case. Maybe it will be better to write: `my_cool_lib`?

> Creating a project or library

> Use the init command to create a Crystal project with the standard directory structure.

```
$ crystal init lib MyCoolLib
      create  MyCoolLib/.gitignore
      create  MyCoolLib/LICENSE
      create  MyCoolLib/README.md
      create  MyCoolLib/.travis.yml
      create  MyCoolLib/shard.yml
      create  MyCoolLib/src/MyCoolLib.cr
      create  MyCoolLib/src/MyCoolLib/version.cr
      create  MyCoolLib/spec/spec_helper.cr
      create  MyCoolLib/spec/MyCoolLib_spec.cr
Initialized empty Git repository in ~/MyCoolLib/.git/
```

**Comment by bcardiff** [comment]
Hi @thooams, this should be reported into  https://github.com/crystal-lang/crystal-book .
Feel free even to submit a PR changing https://github.com/crystal-lang/crystal-book/tree/master/using_the_compiler . I like 🐍 more than 🐫 too.

**Comment by thooams** [comment]
Ok, thanks
