### ISSUE TITLE
Fix disqus links on crystal-lang.org/biog

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal-website#62]
Hi @spalladino @bcardiff 

Currently, If I share a comment using the link provided by discus I get a wrong redirection:

![screenshot_20180602_080439](https://user-images.githubusercontent.com/3067335/40874904-9c10ed66-663b-11e8-86bf-462f4109baee.png)

Then

![screenshot_20180602_080528](https://user-images.githubusercontent.com/3067335/40874906-b802ea4c-663b-11e8-8c3f-659016b2a4c3.png)

And finally:

![screenshot_20180602_080603](https://user-images.githubusercontent.com/3067335/40874909-ccf955c6-663b-11e8-8bc7-ad8f2db49367.png)

Looks like there is a duplicated slash `//` on redirected url :sweat_smile:

**Comment by bcardiff** [comment]
Yeah :-( I've notice that for a while also, but if we change how url are generated all the current comments won't show up. The fix is to conditionally check the date of the post and render the extra `/` on the old ones.

**Comment by matiasgarciaisaia** [comment]
S3 supports double slashes in URLs: https://forums.aws.amazon.com/thread.jspa?threadID=13898

So we should check if we can make them redirect to the single-slashed articles and get the best of both worlds

**Comment by straight-shoota** [comment]
Resolved by #560
