### ISSUE TITLE
Is it too obsesive to ask for text to be justified?

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal-website#674]
I suggest the blog posts to be `text-align:justified`:

<img width="1044" alt="image" src="https://github.com/crystal-lang/crystal-website/assets/5183634/d2a504f1-ad5d-479b-9a60-f8355acd89df">

vs

<img width="1108" alt="image" src="https://github.com/crystal-lang/crystal-website/assets/5183634/54894e5d-1dfb-4bb2-b246-d1d33ef400df">

**Comment by straight-shoota** [comment]
For what reason?
Left aligned text is typically better for readability on long line lengths. Justified makes more sense for dense text in narrower columns (typical newspaper layout).

**Comment by beta-ziliani** [comment]
I don't find it less readable, but since I found 0 blogs with such justification, I call that sufficient justification to close this
