### ISSUE TITLE
[Relaunch] Missing CI sponsor

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal-website#678]
Perhaps we can simply incorporate Works on Arm to the general list of sponsors?

**Comment by straight-shoota** [comment]
I'm not sure what's the deal, exactly. But incorporating them into the sponsor list sounds good to me.

**Comment by straight-shoota** [comment]
Hm, no I don't think so. I can't find a direct money equivalent for our sponsoring package, but I'm pretty sure it's well below the $5,000 corporate sponsors which we put in `top_sponsors`.

The terms from our [sponsorship request](https://github.com/WorksOnArm/equinix-metal-arm64-cluster/issues/286) ask for a "suitable acknowledgement": 

> Approved projects will be expected to provide credit back to Works on Arm in the form of a logo display, blog post, Twitter post, news release, or some other suitable acknowledgement.

So I think don't need to put it anywhere super prominent.
Maybe just a section for "Infrastructure sponsorship" on the sponsors page?

**Comment by beta-ziliani** [comment]
#749 solved this, but GH didn't notice
