### ISSUE TITLE
[Relaunch] Sponsor section in Home

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal-website#680]
- [ ] The "All this is only possible through our generous [sponsors](link) which help sustaining the project." is a bit redundant, maybe remove it?
- [ ] rename SPONSORS to TOP SPONSORS
- [ ] Remove the underline in sponsor's names

**Comment by straight-shoota** [comment]
>  Remove the underline in sponsor's names

Why? I think it makes a lot of sense. The underline highlights links that are part of the content (as opposed to the site UI).

**Comment by beta-ziliani** [comment]
> Why? I think it makes a lot of sense. The underline highlights links that are part of the content (as opposed to the site UI).

The underline makes sense when it's in between text, as in [here](), or in a table, but not when it's the sole component. The fact that you have the image is enough indication that it's clickable.

**Comment by straight-shoota** [comment]
That same link style is used for elements that are not part of body copy text all over the place. We only skip the underline when the link is part of an explicit UI element, such as a button, navigation menu, or card.

An image alone is not sufficient indication of interactivity. We have lots of images that are not links.
