### ISSUE TITLE
Mention Crystal Jobs

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal-website#69]
I've created https://crystaljobs.org - the website for Crystal Job postings with neat editor, e-mail subscriptions and moderation.

I think that it's a good idea to mention this website on the official Crystal site. That would lead to more e-mail (and twitter) subscribers, which would increase the value of Crystal Jobs which would lead to more Job postings which would lead to the language growth itself.

FYI, VueJS has Jobs link on their [website ](https://vuejs.org/)at Ecosystem / News / Jobs and its [about section](https://vuejobs.com/about) confirms that it's a third party website.

If the team has notes or features they'd like to see on Crystal Jobs, let me know.

**Comment by vladfaust** [comment]
A whole week has passed in silence. Any comments?

**Comment by bew** [comment]
You could try to send a PR :)

**Comment by vladfaust** [comment]
I'm not sure where to place the link...

**Comment by CaDs** [comment]
what about `https://crystal-lang.org/community/`

**Comment by bcardiff** [comment]
Hi @vladfaust! Thank you for your work on https://crystaljobs.org! It looks really promising. We'd like to wait a bit and see how it develops before linking it from the official site. The project seems to have a lot of potential and when the right time comes we could certainly add it to `/community`. We feel it's not there yet. Please do announce it in all the community channels, we're looking forward to seeing it gain traction!

**Comment by straight-shoota** [comment]
Closing. https://crystaljobs.org/ seems to be no longer available.
