### ISSUE TITLE
Hello World Example Issues

### ISSUE THREAD

**Issue by Jeeppler** [crystal-lang/crystal-website#7]
Hello,

I wanted to use the hello world example from this page:
https://crystal-lang.org/2013/07/10/hello-world.html

but I encountered the following error:
~~~
Can't infer the type of instance variable '@name' of Greeter

    @name = name.capitalize
    ^~~~~
~~~

I fixed the issue, by adding a `property statement`
~~~
class Greeter
 property name : String
  def initialize(name)
    @name = name.capitalize
  end
  ....
end
~~~

Another issue while trying to compile:

~~~
$ bin/crystal hello.cr
$ ./hello
Hello World
$
~~~

this does not work anymore. It is enough to simply use:

~~~
$ bin/crystal hello.cr
~~~

and if you want to produce an executable:

~~~
$ bin/crystal compile hello.cr
$ ./hello
~~~

My crystal version is: Crystal 0.18.2 (2016-06-17) [on Archlinux]

I think it would be a good idea to update this example. 

_By the way I really like that you show the hello world example as simple `puts`, class and block._

**Comment by asterite** [comment]
Thank you for reporting this! Fixed in https://github.com/crystal-lang/crystal-website/commit/2072fe370f47d943e54ca0cdc2c11fe82bd3d627
