### ISSUE TITLE
Frontpage examples: vertical code overflow

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal-website#714]
The `code` examples on the front page overflow over the main content (firefox 123, linux).

![Capture d’écran de 2024-03-07 18-55-19@2x](https://github.com/crystal-lang/crystal-website/assets/47380/62e704c2-d2cd-41a2-b2fe-c34e784eb6d3)

**Comment by straight-shoota** [comment]
I pushed a commit to fix the background, now it looks like this:

![grafik](https://github.com/crystal-lang/crystal-website/assets/466378/870acee2-42f0-4cde-91db-6017a03e359d)
