### ISSUE TITLE
Licence for the Crystal logo

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal-website#8]
@bcardiff @asterite Hi! :-)

I would like to see the crystal logo in the Wikipedia article like other languages, but Wikimedia takes the licences seriously.

Can Manas include a licence for the Crystal logo?

[Wikimedia guide](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Licensing_tutorial_en.svg/720px-Licensing_tutorial_en.svg.png)
[My question on Gitter](https://gitter.im/crystal-lang/crystal?at=57effa2934a8d5681cd344f0)
[Crystal logo](https://github.com/crystal-lang/crystal-website/blob/85030279ecc658170a0194bae816fe51b0e374ca/images/crystal-h.png)

**Comment by matiasgarciaisaia** [comment]
@faustinoaq no matter what the logo's license is, you should be able to upload it to Wikipedia under the "Fair use" clause. You can see [Java's logo Licensing](https://en.wikipedia.org/wiki/File:Java_programming_language_logo.svg#Licensing), for instance.

It's true - anyway - that we should clearly establish the logo's license 👍

**Comment by faustinoaq** [comment]
@matiasgarciaisaia Hi, thanks for your response!
I already uploaded the Crystal logo to wikipedia. See: [Crystal (programming language)](https://en.wikipedia.org/wiki/Crystal_(programming_language))

I used the same licence of Java and Elixir:
```
=={{int:license-header}}==
{{Non-free logo}}
```

But, Wikimedia is showing me a red warning:
![red-warning](http://i.imgur.com/Qdhswg1.png)

**Comment by faustinoaq** [comment]
I was wrong 😟 
I tried to upload to wikimedia, and the right place for fair-use is wikipedia.
Alright now! 😀
