### ISSUE TITLE
Expired SSL cert on play.crystal-lang.org

### ISSUE THREAD

**Issue by m33m33** [crystal-lang/crystal-website#804]
Hi guys, just a heads up ...

**Comment by beta-ziliani** [comment]
We are aware, thank you. Currently, it's being hosted by @jhass , but he's been unresponsive for a while. We're looking into alternatives.

**Comment by beta-ziliani** [comment]
Now is working, although I created #806 to track the general issue we have today with play.crystal-lang.org
