### ISSUE TITLE
Where can I find more information regarding the spinning controllable logo?

### ISSUE THREAD

**Issue by opensourcechris** [crystal-lang/crystal-website#81]
I want to create one like this except of a directed graph for my site. Apologies in advance as this is not a defect related issue.

**Comment by bcardiff** [comment]
Hi @opensourcechris the entry point is in

https://github.com/crystal-lang/crystal-website/blob/81d45573112f261b0f486a6d172c9deb827ef660/_assets/js/main.js

The 32 polygon is stored in https://github.com/crystal-lang/crystal-website/blob/81d45573112f261b0f486a6d172c9deb827ef660/xml/polyhedron/icosahedron.xml 

The viewer is in https://github.com/crystal-lang/crystal-website/blob/81d45573112f261b0f486a6d172c9deb827ef660/_assets/js/viewer.js . 

It was built by @jkicillof.

Let us know it that ends up in another site :-)
