### ISSUE TITLE
Learn / Getting Started page

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal-website#98]
The "Learn" button on the homepage currently links to https://crystal-lang.org/reference/overview/ which is not a very encouraging landing page for people trying to get to know the language.

We could consider linking to the new `/docs` section (added in #95). But it's not an entirely good fit either. Reading documentation is a part of learning, and learning resources are a part of the documentation. However, I think this call to action should lead to an introductory, specifically tailored to getting new users started. Hence I'd probably call it "Getting Started".

We're still missing a proper getting started guide, but there are already a number of resources that can help with onboarding.

What I'd like to include on this page (roughly in order of priority):

* Link to install page
* Official getting started guide (TODO)
* External tutorials
* Online learning platforms
  * [Crystal track on exercism.io](https://exercism.io/tracks/crystal)
* Link to docs page
* [Online playgrounds](https://github.com/crystal-lang/crystal/wiki/Online-playgrounds)

**Comment by straight-shoota** [comment]
I've collected a few ideas for external tutorials, but haven't actually looked at them closely. We should only present ones that have high quality, are up to date and teach a general understanding of Crystal.

* [An Introduction to the Crystal Programming Language](https://hackernoon.com/an-introduction-to-the-crystal-programming-language-b9e0222b5b5e)
* [Crystal Programming](https://www.youtube.com/watch?v=DxFP-Wjqtsc) (video tutorial)
* [Crystal Lang Tutorial:Installing Crystal Programming Language](https://www.youtube.com/watch?v=KGlHq6ljP8E) (video series)
* [A Quick look at Crystal](https://thoughtbot.com/upcase/videos/a-quick-look-at-crystal)
* [Creating a Cryptocurrency in the Crystal Programming Language](https://www.toptal.com/blockchain/crystal-programming-language-tutorial)
* [Crystal for Rubyists](https://www.crystalforrubyists.com/)

**Comment by bcardiff** [comment]
I would go with

1. Write a better introduction of the book. What information, sections are available, how can be read.
2. Link to that page

Once the book iterate to have a learning flow and not only a language reference this will make more sense. https://forum.crystal-lang.org/t/iterating-the-language-reference-aka-crystal-lang-crystal-book/1080

But I agree that the learn link in the home needs some love.

**Comment by straight-shoota** [comment]
Number 1. is certainly good, but I'm not sure if the book is the perfect place for an in-depth getting starting guide. It would be very difficult to combine a generic language reference with an introduction. Of course, such a guide could be published inside the book, but as an isolated section. I don't think we can adopt the entire book to an incremental learning flow. 

IMO the book should be focused on it's main purpose as a language reference. That might include guides but maybe a dedicated platform would be better.

What do you think about the other resources I've mentioned? Should they be referenced somewhere?

**Comment by bcardiff** [comment]
From the site I would only link official resources for learning + maybe the learning resources forum.

There will always be articles and videos that will be outdated. I prefer the have at least a curated and suggested way to do things in the book. Yet of course not the only one.

The only way to focus on the language itself is to ignore the std-lib. That is more like a spec of the language and I don't think the book will turn into that. There is a balance and mixture of the language, the tools, and the ecosystem. So having guides for different aspects of the development of apps and shards in order to use Crystal as a whole makes sense to me.

**Comment by straight-shoota** [comment]
The main portion of this issue has been sufficiently resolved by the [Crystal Book landing page](https://crystal-lang.org/reference).

I extracted the side issue about collecting learning materials into #287
